import { StarOutlined, EditOutlined, FacebookOutlined, PieChartOutlined, AreaChartOutlined, GlobalOutlined, CloudOutlined, ShareAltOutlined, DeploymentUnitOutlined } from '@ant-design/icons';

const dimension = [
  {
    id: '1',
    icon: EditOutlined,
    name: '文本',
    divHidden: true,
    type: 'input',
    src: 'https://i.loli.net/2021/08/06/jG58g41kotiFA6L.png',
  },
  {
    id: '2',
    icon: EditOutlined,
    name: '简报概述',
    divHidden: true,
    type: 'input',
    src: 'https://i.loli.net/2021/08/06/jG58g41kotiFA6L.png',
  },
  {
    id: '3',
    icon: EditOutlined,
    name: '监测概述',
    divHidden: true,
    type: 'input',
    src: 'https://i.loli.net/2021/08/06/jG58g41kotiFA6L.png',
  },
  {
    id: '4',
    icon: CloudOutlined,
    name: '关键词云',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/YQ4OJ8mIBwslAgd.png',
  },
  {
    id: '5',
    icon: PieChartOutlined,
    name: '敏感度分布',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/4i3qbvolgCWJnMF.png',
  },
  {
    id: '6',
    icon: PieChartOutlined,
    name: '来源分布',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/Pbq7JstQdkgCSf6.png',
  },
  {
    id: '7',
    icon: AreaChartOutlined,
    name: '总量趋势',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/ijHnuAFZa4RIohV.png',
  },
  {
    id: '8',
    icon: AreaChartOutlined,
    name: '来源趋势',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/UyMNzwhlVstPQxr.png',
  },
  {
    id: '9',
    icon: GlobalOutlined,
    name: '地域分布',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/UW1FARkYOEdpVob.png',
  },
  {
    id: '10',
    icon: PieChartOutlined,
    name: '情感分析',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/9p6lZMAsOaLESPB.png',
  },
  {
    id: '11',
    icon: AreaChartOutlined,
    name: '情感趋势图',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/iZNu4CWMYvOH6Up.png',
  },
  {
    id: '12',
    icon: ShareAltOutlined,
    name: '事件溯源',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/08/06/cODJ8HMgZEiB9sp.png',
  },
  {
    id: '13',
    icon: ShareAltOutlined,
    name: '微博溯源树形图',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/c1hAGWNijotMFED.png',
  },
  {
    id: '14',
    icon: DeploymentUnitOutlined,
    name: '微博溯源扩散图',
    divHidden: true,
    type: 'image',
    src: 'https://i.loli.net/2021/09/02/urgUqTSEBNi1s4t.png',
  },
];

export default dimension;
